function wallBeliefs = initWallBeliefs(optWalls)
% INITWALLBELIEFS Initialize optional-wall existence beliefs.

numWalls = size(optWalls, 1);
wallBeliefs = repmat(struct( ...
    'geometry', zeros(1, 4), ...
    'logOdds', 0, ...
    'probPresent', 0.5, ...
    'observationCount', 0, ...
    'status', 'unknown'), numWalls, 1);

for i = 1:numWalls
    wallBeliefs(i).geometry = optWalls(i, :);
end
end
